# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [ ]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
x = dataset.iloc[: ,: -1].values
y = dataset.iloc[: , -1].values

In [ ]:
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
X_train, X_test , y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0 )

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 24.4100
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 23.8318
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 24.4300
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 24.8972
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 25.2223
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 24.3890
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 24.1355
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 23.9856
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 23.9470
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 24.1437
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 24.0689
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 24.9123
E

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate(( y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))



[[432.45 431.23]
 [460.75 460.01]
 [466.67 461.14]
 ...
 [473.39 473.26]
 [440.51 438.  ]
 [457.46 463.28]]
